name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.7'
          channel: 'stable'

      - name: Install dependencies
        run: cd quakesafe && flutter pub get

      - name: Build APK
        run: cd quakesafe && flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: quakesafe-apk
          path: quakesafe/build/app/outputs/flutter-apk/app-release.apk
